### ISSUE TITLE
Stat Modify Dialogue

### ISSUE THREAD

**Issue by bithir** [pwatson100/symbaroum#115]
Need improvement for sizes and fonts.
![Screenshot_2021-02-25_20-32-45](https://user-images.githubusercontent.com/19734037/109213604-b46a2b80-77a8-11eb-8ba8-d3b82af3932f.png)

**Comment by Khaali-dev** [comment]
Weird.
It looks much better on my system
![image](https://user-images.githubusercontent.com/67241204/109530269-cf91af80-7ab6-11eb-8fc0-777264744bc0.png)
