### ISSUE TITLE
Feature Request: Move non-English language files to their own modules

### ISSUE THREAD

**Issue by Rangertheman** [pwatson100/symbaroum#178]
To make the Compendium tab less cluttered and to make the system less dependant on up-to-date translations, I would suggest moving the non-English language files into their own modules, e.g. by utilizing the Babele module. 

(Sidenote: I have a module for Swedish, mostly built upon Weymyss' translations, sitting in a private repo. I would gladly hand it over to the project (or keep it updated with Weymyss' help)).

**Comment by bithir** [comment]
In the end, we decided for a different solution - from next release, we will strip away languages compendiums, if a translated one exists. There is an option to retain all english ones, with the translated ones as well.
