### ISSUE TITLE
Compendium SV-Powers SV-Trais still has multiple languages and translations are missing

### ISSUE THREAD

**Issue by Sherigan81** [pwatson100/symbaroum#180]
Hello! First off. GOOD JOB on this stuff!

Second, I noticed that the swedish compendiums have mixed languages in it still, as examples some powers are in there without translations. I.e

(Lay on Hands, Mark of torment, Natures embrace, Phychic trust etc)

Bithir asked me to submit it, since he didn't know if they were still WIP or not. So I did =)

**Comment by Weymyss** [comment]
I've gone through all the swedish compendiums now and fixed them. Also added armors and weapons. 
Will be available in 0.8 if I understand correctly from Bithir.
