### ISSUE TITLE
Weapons and Armos only appears on sheet after pressing F5

### ISSUE THREAD

**Issue by AndrewsChetera** [pwatson100/symbaroum#183]
When dragging weapons or armor, they only appear on the sheet after pressing F5.

The same issue occurs when changing the weapon or armos to active. The change only takes affect after pressing F5.

Only happens on version 2.22. Version 2.20 works fine.

I'm using Foundry VTT 7.9.0 with some modules, but the issue also happens without modules or on a fresh world.

**Comment by bithir** [comment]
This has been seen once before - that user solved it with a full re-install of foundry.  If you contact us on the Foundry discord, #free-league channel, we might be able to have look if we can see something in particular that occurs in your system.

**Comment by AndrewsChetera** [comment]
Confirmed! A full reinstall solves the issue!

Thanks a lot!

**Comment by Flintwyrm** [comment]
This is still happening in a way. if you have Staff Fighter in a sheet it will not let you add weapons into the sheet.

**Comment by Flintwyrm** [comment]
If you have weapons in your inventory and you add Staff Fighting it wont add the ability. if you f5 refresh it appears in your sheet but then your weapons dont show up and you cant add any weapons. 
![Screenshot_2348](https://user-images.githubusercontent.com/60701064/126100124-8135520a-ccdd-4507-8960-474fde882349.png)
