### ISSUE TITLE
NPC importer not working 0.8.6

### ISSUE THREAD

**Issue by Flintwyrm** [pwatson100/symbaroum#214]
I went to use the NPC importer macro and I got this error.
![Screenshot_2194](https://user-images.githubusercontent.com/60701064/124012745-7cb9fd00-d9af-11eb-95ae-6e35cb77a1a0.png)

**Comment by bithir** [comment]
As discussed on discord - likely related to https://gitlab.com/foundrynet/foundryvtt/-/issues/5026
