### ISSUE TITLE
Feature Request - Don't show Pain Threshold for undead

### ISSUE THREAD

**Issue by pwatson100** [pwatson100/symbaroum#228]
The sheet calculates the Pain Threshold for Undead and Abominations when there should not be any.

**Comment by bithir** [comment]
Applies for Corruption threshold and Abomination as well - which is also the case for Abominations.

**Comment by bithir** [comment]
> Applies for Corruption threshold and Abomination as well - which is also the case for Abominations.

Note that Abominations are a bigger issue - as they have no built-in trait that we can use to identify what is an abomination.
