### ISSUE TITLE
Damage modification on powers

### ISSUE THREAD

**Issue by THZ74** [pwatson100/symbaroum#231]
Weapons have a field where you can enter for example -1 or +1d8 to modify the damage, but powers dont.

This is sometimes needed if something in the area/ world/ situation/ target/ etc modifies the damage.

For a more specific example:
A Theurg cast a Prios Burning Glass and is in the possession of a artifact in the form of:  
Water of the dusk. Which only affect the spells effect for once every scene, so the program dont know when its used.
(you add 1d3-1 to simulate an increased dice-tier....)

Without any coding knowledge it seems to me that this is not a bug but merely an oversight and should be fixable without too much of an hazzle (as I said no knowledge what so ever)

Respectfully THZ

**Comment by Khaali-dev** [comment]
This has been integrated in 3.0.4
