### ISSUE TITLE
Swedish language file , misspelling and or suggestions

### ISSUE THREAD

**Issue by THZ74** [pwatson100/symbaroum#233]
Misspellings or printerror

Line 218
reads : "COMBAT.CHAT_FAILURE": " miss.",
should read: "COMBAT.CHAT_FAILURE": " missar.",

Line 389
reads: "POWER_ANATHEMA.CHAT_FAILURE": " skingrar.",
should read: "POWER_ANATHEMA.CHAT_FAILURE": " misslyckas.",

Suggestions (not in any way sure)
Line 146:
reads:  "ARMOR.BONUS_ONLY": "Travbar bepansring",
maybe change to :  "ARMOR.BONUS_ONLY": "Adderbar bepansring",

I dont have a really good alternative here. The words I can think of is
Travbar - very unusual wording (not wrong per se, but "clunky"
Stapelbar - more usual wording but its maybe not the right kind of "stacking"
Adderbar - more in line what you are after, but not sure. 

Questions?
Line 24
reads "ABILITY_LABEL.BLESSINGS":"Signerier",
maybe: "ABILITY_LABEL.BLESSINGS":"Välsignelser",

I dont have the correct book with me to check. Have sent out a word to the person who have them asking. "Signerier" is a bit of a strange word, but not wrong. I first thought it was a misspelling of Symbolism accually.

Will add to this list when/ if I find more things to comment on

**Comment by THZ74** [comment]
Now seen it in game.
Line 146 should read: 
"ARMOR.BONUS_ONLY": "Extra bepansring",
or
"ARMOR.BONUS_ONLY": "Ytterligare bepansring",

**Comment by THZ74** [comment]
Have now read the swedish version of Blessings and the official text is "Signerier" so my bad there.
So Line 24 is correct.

**Comment by bithir** [comment]
Be aware that there are restrictions of length on the character sheet, so there are text that just will not fit the labels and thus needs to be shortened.

**Comment by Weymyss** [comment]
Will fix all above (except Signerier). Thanks for checking! :-)

**Comment by bithir** [comment]
Gone live - closing
