### ISSUE TITLE
Ability - Medicus

### ISSUE THREAD

**Issue by THZ74** [pwatson100/symbaroum#235]
Short version
Medicus needs a "healing effect modification" box like weapons have a "damage modification"

**Target required**
A design decision?

I'd say that the players has rolled more times out of combat without a targeted token then within combat with a token targeted.
Mainly due to the ruling that Medicus take more time to apply then just 1 Action, but I say that the "I examine the corpse" rolls are most likely more then the "I heal my friend" rolls.

Not sure. The wordings have to change if you remove target. As it is right now you roll [Cunning] for examinations and Medicus for healing. 
(probably very table-dependent. But we usually switch to an atmospheric picture or a "area/ world-map" right as the combat ends and patching up is done "out of combat")

I have an idea that might work (I have no coding knowledge)
It has to do with the question pop-up that you have to answer....but first the other thought...

**Question pop-up about Herbal cure or not**
One feedback is that yes Herbal Cure is the usual, but Holy water isnt a choice, neither is the special case found in one supplement that I can remember (there are probably more)

Having a question popup what you use including all variants might not be efficient. Is it possible to spell it out something like :
Character uses medicus helped by alchemical elixirs.
Followed by a "Damage modifier" (as from weapon attacks) on the next screen where you can enter if its +1, +2 or +1d4

(No idea how to code for the -1 temp corruption....probably just spell it out for the player/gm to do manually)

**Finaly a question.**
Would it be possible to change the pop-up to :
1. Do you heal
2. Do you examine

And if heal you enter a "healing modifier" or is it possible to answer another question-popup?

Final words.
If I could change ONE thing it would be to include a "healing modifier" (as from weapons) that would solve most things without to much work (I think)

Thanks once again for the awesome work you do.
Our group is on the verge to go over to Forge, its mainly the investment and familiarity that keeps us in the old system.

Respectfully
THZ

**Comment by Khaali-dev** [comment]
Very good ideas.
I integrated a "custom healing formula" in the dialog box. If a formula is entered in th box it will replace the normal one.
Also a "simple medicus roll" option in the dialog, no healing will be done.
Finaly, you'll be able to use medicus without a target, it will do a simple medicus roll.

Functionality will be in the next release.
