### ISSUE TITLE
Abilities - effect sometimes applied without choosing level of skill  (only novice effects)

### ISSUE THREAD

**Issue by THZ74** [pwatson100/symbaroum#250]
I have noticed that some skills applies the effect even if you dont check the [Novice] box.
Not seen any difference with Enhanced combat checked or unchecked

For example.
Man-at-Arms increases your armor die even if [Novice] is unchecked
Shield Fighter increases your defense (if unchecked) but dont increase weapon die without checking the box first
Staff Fighter increases your defense by one if you carry any kind of polearm without checking the box.

Backstab dont need the box checked to apply the change to the weapon pop-up where you can choose "apply backstab damage"

On the contrary 
Two Hand Force requires you to click the box before effect on damage die
Natural Warrior the same
Pole Arm Mastery the same
Marksman the same

And as above Shield fighters effect on the 1h weapon comes into effect only after you checked the box.

Beserker needs the box checked to apply effect
Beast Lore needs adept checked to apply "add beastlore damage" option in rolling weapon damage "popup"

Not implemented?
Swordsaint does nothing with out without checking the box, I assume its not coded yet?

My guess its not as much a bug as different people and or time you coded them?

It works, so its maybe more of a "glitch" then a bug?

Respectfully
THZ

**Comment by Khaali-dev** [comment]
Corrected in next release
