### ISSUE TITLE
Man-at-Arms (Adept) effect on Impeding (Affecting things it shouldn't)

### ISSUE THREAD

**Issue by THZ74** [pwatson100/symbaroum#251]
I noticed that Man-at-Arms changed the Impeding value on the character sheet directly. But it creates some errors.

This way MaA have an effect on powers used (and it shouldnt Core pp118)

So in essence
MaA effect
Defense - Should
Abilities like acrobatics - Should

Powers - Should NOT   (this is Armored Mystics effect)

Side note
Armored Mystic don't seem to have any effect. My guess its not coded yet?

Solutions (I have no coding ability so my ideas might be stupid)
1. Two Impedinging values on the sheet (one for defense and abilities ...and another for powers)
Pro- Probably easier?
Con - not elegant?

2. Hidden values on the sheet (as above)
Pro - probably even easier since you dont have to change graphic
Con - not transparant

3. Let the Impeding value stand unaffected on the sheet but make the calculations for each ability.
Pro - more exact
Con - alot of work for very little gain 

Respectfully
THZ

**Comment by Khaali-dev** [comment]
Corrected in 3.1.1
