### ISSUE TITLE
Ability - Staff Fighting

### ISSUE THREAD

**Issue by THZ74** [pwatson100/symbaroum#252]
The novice ability adds +1 Defense if you have a polearm equiped, but not +2 if you have a staff.

Not sure if this is intentional or not.
My guess is that its hard for the code to recognise "staff". Instead you have coded it for "long". But I havent tested that I realized just now.

Respectfully
THZ

**Comment by bithir** [comment]
There is no possible way for us to know what is a "staff" - we support multiple languages and there is no consistent way for us to know that a weapon is some sort of staff.
The system has allowance to have this resolved, so for the character with this ability, you can open the bonus tab for any staff that they have and put the suitable number you need in the "Defense".  This will take effect when the weapon is wielded.

**Comment by THZ74** [comment]
I suspected as much.

I noticed it and wanted to bring it to attention if it was unintended.


Please say if my observations anoy more than they help. The intention is to help in the way I can to get a functional module.


Respectfully
Thz

Hämta Outlook för Android<https://aka.ms/AAb9ysg>

________________________________
