### ISSUE TITLE
Ability - Backstab (master) have no effect

### ISSUE THREAD

**Issue by THZ74** [pwatson100/symbaroum#254]
(First off, brilliantly coded. If you dont check for advantage it wont apply the effect which is very thought out)

But to the issue.
The novice and adept parts seems to work flawlessly but the master part dont have any effect.
(With Enhanced combat enabled of course)

(n) = +1d4 damage 
(a) = +1d4 bleeding
(m) = exchange the novice (+1d4) for the master effect (+1d8)

If you have master activated right now in Foundry you still do the weapon+1d4 (advantage)+1d4(backstab)
you should do weapon + 1d4 (advantage) +1d8 (backstab)

I found a bug report from march but couldnt find any text relating to this so it might be a known issue

Respectfully
THZ

**Comment by Khaali-dev** [comment]
Corrected in 3.1.1

**Comment by Khaali-dev** [comment]
Corrected in 3.1.1
