### ISSUE TITLE
Combat - Characters use the BASE damage as if they were NPCs.

### ISSUE THREAD

**Issue by kufferino** [pwatson100/symbaroum#318]
When I make two tokens to fight (a player against an NPC), the player will always use BASE damage (as an NPC) instead of rolling a dice for his damage (1dx). 

The error occurs only in attack, not in defense. And I am using advanced combat.

![imagen](https://user-images.githubusercontent.com/74428751/134550277-de2b2df2-4f63-426d-803d-780bc471cc02.png)

**Comment by Khaali-dev** [comment]
corrected in RT8

**Comment by Khaali-dev** [comment]
corrected in RT8
