### ISSUE TITLE
Option to see all relevant dice when using „dice so nice“ module.

### ISSUE THREAD

**Issue by Pheromant** [pwatson100/symbaroum#357]
Hi there, 

when using the Enhanced Combat options many rolls are unified and results are posted in the chat. 
Sadly only the d20 Roll is visualized by DsN, while 
Damage, Armor and corruption dice are not visually rolled. Even though they are calculated and applied correctly.
Me and my players love to see dice rolling, so it would be great if we could see them all.

Thanks for reading
Pheromant

**Comment by bithir** [comment]
Somewhat related to #190 - I believe the DsN made changes to support us, so there is a potential here to do this completely different for both normal mode and EC mode.

**Comment by bithir** [comment]
I believe mostly or completely fixed in #378 - scheduled for 3.1.4
