### ISSUE TITLE
Alternative Damage is affected by target's armor roll

### ISSUE THREAD

**Issue by LordMallus** [pwatson100/symbaroum#480]
I'm creating some new creatures that attack with Alt. Damage (Strong/Resolute/etc.) and when the creature attacks a character using EC it still allows the character to roll armor and the Alt. Damage is modified by that roll.
If the armor roll is lower than the damage, it does add a negative modifier to the correct Attribute.
But it seems like those attacks should ignore armor.

![image](https://user-images.githubusercontent.com/90716934/169061796-c2474c11-6c45-40a9-8d52-31398930aed5.png)
![image](https://user-images.githubusercontent.com/90716934/169061848-081b9894-f71c-47b4-b932-9cf11c862487.png)

**Comment by bithir** [comment]
System do not really support "ignore armor" very well, so likely we will do this in bits.  It will not be for next release :)

**Comment by LordMallus** [comment]
No worries, it's something I can probably work around.  Thanks!
