### ISSUE TITLE
Running Player Tour after GM Tour fails to show attributes

### ISSUE THREAD

**Issue by farling42** [pwatson100/symbaroum#586]
I ran the "Character Sheet Introduction (GM)" tour and everything worked properly.

I followed this by running the "Character Sheet Introduction (Player)" tour, and when it got to the step to describe the attributes, the Actor sheet was still showing the Notes tab (because the GM tour had showed that tab last).

---

I assume a simple selection of the "MAIN" tab is required in the tour before the Attribute description is displayed.

**Comment by bithir** [comment]
Will be revisited as part of Foundry VTT v11 work - a lot of the tours stop working in v11 during our initial testing of v11.

**Comment by bithir** [comment]
Embarrassing when it is my changes which made this happen :)
Tours finds elements based on selectors - I moved us away from table cells to list items that is causing this issue.

**Comment by bithir** [comment]
Fixed as part of 5.0
