### ISSUE TITLE
Auto calculate initiative in Combat tracker

### ISSUE THREAD

**Issue by MrDirac** [pwatson100/symbaroum#613]
When running combat in Symbaroum on Forge it would be very useful if PC and NPC initiative was automatically calculated when they are placed in the combat tracker rather than needing to click on the roll all button at the top of the combat tracker. Since there is no random element to initiative in Symbaroum, this would reduce the time taken to set up tracker ready for the combat to begin. 

Originally raised on Discord - Foundry Virtual Tabletop - Free League by MrDirac on 26/06/23 at 22:51 UK time. Many thanks!

**Comment by bithir** [comment]
Will be included in next release.
![image](https://github.com/pwatson100/symbaroum/assets/19734037/18037c19-42a7-48ef-bab2-a3940a8a23bb)

**Comment by bithir** [comment]
Note, you will still need to roll for people that join combat after it has started.

**Comment by MrDirac** [comment]
Thank you very much! Massive appreciation to you, Paul and the team!

**Comment by MrDirac** [comment]
Thanks Bithir! Much appreciated. Kind regards, IanSent from my iPadOn 7 Jul 2023, at 15:16, bithir ***@***.***> wrote:﻿
Closed #613 as completed.
