### ISSUE TITLE
FoundryVTT errors with corerules and starterset

### ISSUE THREAD

**Issue by yjeroen** [pwatson100/symbaroum#640]
Errors in the console when these modules are loaded:

![image](https://github.com/pwatson100/symbaroum/assets/1303988/91401b4e-6479-448c-8806-7e954a63f012)

**Comment by pwatson100** [comment]
I don't recall seeing this before.  Could you provide the following information please: 
Foundry VTT version,
Hosting solution,
Symbaroum Core version,
Core Rules version,
Starter Set version,

Were all the assets imported prior to this?

**Comment by yjeroen** [comment]
FoundryVTT 11.311
Electron windows client
Symbaroum 4.3.2
Symbaroum Adventures Collection 2.0.3
Symbaroum Core Rulebook 2.0.1
Symbaroum Starter Set 2.0.2

The assets were imported when FoundryVTT was at v9.

**Comment by bithir** [comment]
@yjeroen You able to confirm this so that I can close this issue?

**Comment by yjeroen** [comment]
@bithir, apologies I somewhere missed the notitication.

1. Disabled Starter Set + Core Rulebook & reload
2. Enabled Starter Set  & reload
3. Re-Imported Starter set
4. No longer error 
5. Enabled Core Rulebook & reload
6. Re-Imported Core Rulebook set
7. No longer errors

Please note it did recreate Folders that I deleted due to merging and renaming folders. Wish it hadn't done that but at least the errors are gone now..
