### ISSUE TITLE
Strangler ability calculation

### ISSUE THREAD

**Issue by Darkwolf627** [pwatson100/symbaroum#649]
In Symbaroum, the Strangler ability is supposed to ignore armor. But when you roll it against an opponent it subtracts the armor. Unless I am missing something this is incorrect.  Any insight into this?

**Comment by Khaali-dev** [comment]
corrected in 4.4.3

**Comment by Darkwolf627** [comment]
Thanks.
    On Tuesday, January 23, 2024 at 01:17:03 PM EST, Khaali ***@***.***> wrote:  
 
 


corrected in 4.4.3
