### ISSUE TITLE
Foundry V12

### ISSUE THREAD

**Issue by BytomMan** [pwatson100/symbaroum#661]
Number of button issues with FVTT V12:

1) ESC won't bring up menu to reload.
2) Certain menus, such as when editing scenes, SAVE won't exit the screen and it will stay locked on that menu.
3) Transition from daylight to night to daylight won't take effect unless exiting the application.

**Comment by bithir** [comment]
Neither of these are controlled by the Symbaroum system.  I believe this are just normal Foundry VTT core functionality.

However:
1. ESC brings up the menu to reload to for me in all versions of Foundry VTT, including Foundry VTT v12.
2. Save on editing scenes closes the menu for me
3. Symbaroum system has no concept of day or night, so this must be module controlled

If you recently upgraded to v12 - I would tentatively suggest that you do a try to do a hard reload (Ctrl-F5) and see if it solves some issues.  If not, check out #troubleshooting on the Foundry VTT Discord.
